# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Set command line editin to use vi/vim
set -o vi

# Export JMX Port for Kafka monitoring
export JMX_PORT=9990

