# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Set command line editin to use vi/vim
set -o vi

# Sparks needs sf4j-simple.jar to be in the classpath
export SPARK_CLASSPATH=/usr/share/java/slf4j-simple.jar 

